use strum_macros::EnumIter;

#[derive(Debug, Eq, PartialEq, PartialOrd, Copy, Clone, EnumIter)]
pub enum Action {
    Pass = 0,
    Pick = 1,
    CallH = 2,
    CallD = 3,
    CallS = 4,
    CallC = 5,
    HAPlay = 6,
    HKPlay = 7,
    HQPlay = 8,
    HJPlay = 9,
    HTPlay = 10,
    H9Play = 11,
    DAPlay = 12,
    DKPlay = 13,
    DQPlay = 14,
    DJPlay = 15,
    DTPlay = 16,
    D9Play = 17,
    SAPlay = 18,
    SKPlay = 19,
    SQPlay = 20,
    SJPlay = 21,
    STPlay = 22,
    S9Play = 23,
    CAPlay = 24,
    CKPlay = 25,
    CQPlay = 26,
    CJPlay = 27,
    CTPlay = 28,
    C9Play = 29,
    HADiscard = 30,
    HKDiscard = 31,
    HQDiscard = 32,
    HJDiscard = 33,
    HTDiscard = 34,
    H9Discard = 35,
    DADiscard = 36,
    DKDiscard = 37,
    DQDiscard = 38,
    DJDiscard = 39,
    DTDiscard = 40,
    D9Discard = 41,
    SADiscard = 42,
    SKDiscard = 43,
    SQDiscard = 44,
    SJDiscard = 45,
    STDiscard = 46,
    S9Discard = 47,
    CADiscard = 48,
    CKDiscard = 49,
    CQDiscard = 50,
    CJDiscard = 51,
    CTDiscard = 52,
    C9Discard = 53,
}

#[derive(Copy, Clone)]
pub enum FlippedChoice {
    PickedUp,
    TurnedDown,
}
